name: apk_ieee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  fl_chart: ^1.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    # Registro explícito de imágenes usadas en el Sensor Dashboard
    - assets/images/sensor_dashboard/s_temp.png
    - assets/images/sensor_dashboard/s_humedad.png
    - assets/images/sensor_dashboard/s_ph.png
    - assets/images/sensor_dashboard/s_tds.png
